[package]
name = "epochfs"
version = "0.0.1"
edition = "2021"
description = "EpochFS is a versioned cloud file system with git-like branching, transaction support."
license = "Apache-2.0"

[dependencies]
